## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
before_install:
  - rvm get stable  # work around rvm bug on osx

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Match"); Pkg.test("Match"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Match")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # publish documentation
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Match")); include(joinpath("docs", "make.jl"))'
